version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'uvicorn main:app --host 0.0.0.0 --port 8080'
    ports:
      - 8001:8080
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command : 'python consumer.py'
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ******
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33067:3306"
