# Generated by Django 4.2.7 on 2023-11-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_id_alter_product_likes_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
