"""update price column

Revision ID: 0055c1be2e69
Revises: 161fde6073cd
Create Date: 2023-11-29 18:42:28.051557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0055c1be2e69'
down_revision: Union[str, None] = '161fde6073cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
