"""update table

Revision ID: 161fde6073cd
Revises: 32366bbf5da0
Create Date: 2023-11-29 18:14:23.793845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '161fde6073cd'
down_revision: Union[str, None] = '32366bbf5da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('likes', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
